/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoHead;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import java.text.*;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Printer;
import javax.swing.JTextArea;


/**
 *
 * @author J.RILEY
 */
public class AutoHead extends javax.swing.JFrame {

     double FordMustangGT = 30000;
        double BMW_X6 = 45000;
        double BenzCLK = 40000;
        double Chevolet_Camaro = 28000;
        double Jeep_Wrangler = 50000;
        double RollsRoyce_Phantom = 65000;  
        
    /**
     * Creates new form AutoHead
     */
    public AutoHead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCustomer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSOR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDownP = new javax.swing.JTextField();
        jComboBoxPOID = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxStereo = new javax.swing.JCheckBox();
        jCheckBoxLeather = new javax.swing.JCheckBox();
        jCheckBoxGPS = new javax.swing.JCheckBox();
        jCheckBoxTint = new javax.swing.JCheckBox();
        jCheckBoxMPB = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxCar = new javax.swing.JComboBox<>();
        jTextFieldCost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxTradeIn = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldValue = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldTax = new javax.swing.JTextField();
        jTextFieldSubtotal = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));

        jLabel1.setBackground(new java.awt.Color(255, 204, 153));
        jLabel1.setFont(new java.awt.Font("Silom", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*DON ROSS AUTOHEAD*");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 183;
        gridBagConstraints.ipady = -23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 10, true));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Customers Details");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel3.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jLabel3.setText("Customer ID");

        jTextFieldCustomer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldCustomer.setOpaque(true);
        jTextFieldCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jLabel4.setText("FirstName");

        jTextFieldFirstname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldFirstname.setOpaque(true);
        jTextFieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jLabel5.setText("Surname");

        jTextFieldSurname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldSurname.setOpaque(true);
        jTextFieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSurnameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jLabel6.setText("Address");

        jTextFieldAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldAddress.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jLabel7.setText("Phone No.");

        jTextFieldPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldPhone.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jLabel8.setText("State Of Residence");

        jTextFieldSOR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldSOR.setOpaque(true);

        jLabel9.setText("DOWN PAYMENT");

        jTextFieldDownP.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldDownP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDownP.setText("write amount to deposit here");
        jTextFieldDownP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextFieldDownP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDownPActionPerformed(evt);
            }
        });

        jComboBoxPOID.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jComboBoxPOID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prove Of Identification", "NATIONAL ID", "VOTERS CARD", "INTERNATIONAL PASSPORT" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(124, 124, 124))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldDownP, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))))
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(246, 246, 246)
                                .addComponent(jComboBoxPOID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSOR, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(jComboBoxPOID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSOR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jTextFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDownP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jTextAreaReceipt.setBackground(new java.awt.Color(255, 204, 153));
        jTextAreaReceipt.setColumns(20);
        jTextAreaReceipt.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jTextAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReceipt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 327;
        gridBagConstraints.ipady = 477;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 5);
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 10, true));

        jCheckBoxStereo.setText("Stereo System");

        jCheckBoxLeather.setText("Leather Interior");
        jCheckBoxLeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLeatherActionPerformed(evt);
            }
        });

        jCheckBoxGPS.setText("G.P.S");
        jCheckBoxGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGPSActionPerformed(evt);
            }
        });

        jCheckBoxTint.setText("Window Tint");

        jCheckBoxMPB.setText("Matte Paint Body");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxStereo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxMPB))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxLeather)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxTint, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxStereo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxMPB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxLeather, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxGPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -5;
        gridBagConstraints.ipady = -44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 5, true));

        jComboBoxCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT CAR", "FordMustangGT", "BMW_X6", "BenzCLK", "Chevolet_Camaro", "Jeep_Wrangler", "RollsRoyce_Phantom" }));
        jComboBoxCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCarActionPerformed(evt);
            }
        });

        jTextFieldCost.setBackground(new java.awt.Color(153, 255, 153));

        jLabel10.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("COST");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBoxCar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldCost)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 8, true));

        jComboBoxTradeIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRADE IN CAR", " ", " " }));
        jComboBoxTradeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTradeInActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VALUE");

        jTextFieldValue.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTradeIn, 0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTradeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jPanel6, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 10, true));
        jPanel7.setForeground(new java.awt.Color(255, 102, 0));

        jLabel12.setText("TAX");

        jLabel13.setText("SUBTOTAL");

        jLabel14.setText("TOTAL");

        jTextFieldTax.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        jTextFieldTax.setText("please wait....");

        jTextFieldSubtotal.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        jTextFieldSubtotal.setText("please wait....");
        jTextFieldSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubtotalActionPerformed(evt);
            }
        });

        jTextFieldTotal.setFont(new java.awt.Font("Silom", 1, 14)); // NOI18N
        jTextFieldTotal.setText("please wait....");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 24, 0);
        getContentPane().add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 10, true));

        jButtonTotal.setFont(new java.awt.Font("Courier", 1, 18)); // NOI18N
        jButtonTotal.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTotal.setText("TOTAL");
        jButtonTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButtonTotal.setOpaque(true);
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Courier", 1, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 0, 0));
        jButtonExit.setText("EXIT");
        jButtonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit.setOpaque(true);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Courier", 1, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(0, 0, 204));
        jButtonReset.setText("RESET");
        jButtonReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.setOpaque(true);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonPrint.setFont(new java.awt.Font("Courier", 1, 18)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(0, 0, 204));
        jButtonPrint.setText("PRINT");
        jButtonPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrint.setOpaque(true);
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 5);
        getContentPane().add(jPanel8, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerActionPerformed

    private void jTextFieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameActionPerformed

    private void jTextFieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSurnameActionPerformed

    private void jTextFieldDownPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDownPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDownPActionPerformed

    private void jCheckBoxLeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLeatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxLeatherActionPerformed

    private void jCheckBoxGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxGPSActionPerformed

    private void jTextFieldSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubtotalActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        cCustomer iExit = new cCustomer();
        
        try {
            iExit.iExitSystem();
        }catch (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "confirm if you want to exit");
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        JTextField cleartext = null;
        try{
        for (Component c: jPanel2.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
                jTextFieldCost.setText("");
                jTextAreaReceipt.setText("******please wait or Input Sales Details*********");
                jTextFieldTax.setText("");
                jTextFieldSubtotal.setText("");
                jTextFieldTotal.setText("");
                jTextFieldValue.setText("");
                jTextFieldCost.setText("");
                jComboBoxCar.setSelectedItem("SELECT CAR");
                jComboBoxTradeIn.setSelectedItem("TRADE IN CAR");
                jComboBoxPOID.setSelectedItem("Prove Of Identification");
                jCheckBoxStereo.setSelected(true);
                jCheckBoxGPS.setSelected(true);
                jCheckBoxMPB.setSelected(true);
                jCheckBoxLeather.setSelected(true);
                jCheckBoxTint.setSelected(true);
                
            }
        }
        }catch (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "confirm if you want to RESET");
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        try {
            
            jTextAreaReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(AutoHead.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cCars ca = new cCars();
        jComboBoxTradeIn.addItem(ca.getTrade_In_1());
        jComboBoxTradeIn.addItem(ca.getTrade_In_2());
        jComboBoxTradeIn.addItem(ca.getTrade_In_3());
        jComboBoxTradeIn.addItem(ca.getTrade_In_4());
        jComboBoxTradeIn.addItem(ca.getTrade_In_5());
        
        jCheckBoxStereo.setSelected(true);
        jCheckBoxLeather.setSelected(true);
        jCheckBoxGPS.setSelected(true);
        jCheckBoxTint.setSelected(true);
        jCheckBoxMPB.setSelected(true);
    }//GEN-LAST:event_formWindowActivated

    private void jComboBoxCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCarActionPerformed
        // TODO add your handling code here:
       
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT"))
        {
            String Car = String.format("$%.2f", FordMustangGT);
            jTextFieldCost.setText(Car);
        }  
        
        if (jComboBoxCar.getSelectedItem().equals("BMW_X6"))
        {
            String Car = String.format("$%.2f", BMW_X6);
            jTextFieldCost.setText(Car);
        }
        
        if (jComboBoxCar.getSelectedItem().equals("BenzCLK"))
        {
            String Car = String.format("$%.2f", BenzCLK);
            jTextFieldCost.setText(Car);
        }
        
         
        if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro"))
        {
            String Car = String.format("$%.2f", Chevolet_Camaro);
            jTextFieldCost.setText(Car);
        }
        
        
          if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler"))
        {
            String Car = String.format("$%.2f", Jeep_Wrangler);
            jTextFieldCost.setText(Car);
        }
          
          
          if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom"))
        {
            String Car = String.format("$%.2f", RollsRoyce_Phantom);
            jTextFieldCost.setText(Car);
        }
    }//GEN-LAST:event_jComboBoxCarActionPerformed

    private void jComboBoxTradeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTradeInActionPerformed
        // TODO add your handling code here:
        if (jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {
            jTextFieldValue.setText("$10000"); 
        }
        
        if (jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {
            jTextFieldValue.setText("$8000"); 
        }
        
         
         if (jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        {
            jTextFieldValue.setText("$6000"); 
        }
        
         
         if (jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {
            jTextFieldValue.setText("$4000"); 
        }
         
          if (jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {
            jTextFieldValue.setText("$2000"); 
        }
    }//GEN-LAST:event_jComboBoxTradeInActionPerformed

         
        public double mcTax = 0.90;
        public double cFindTax(double cAmount){
            
            double FindTax = (cAmount * mcTax);
            return FindTax;
        }
    
    
    
    
    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        // TODO add your handling code here:
        CarAccessory Accessory = new CarAccessory();
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT") && jComboBoxTradeIn.getSelectedItem().equals("TRADE IN CAR"))
        {
            String iSubtotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(FordMustangGT + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount()+cFindTax(FordMustangGT + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }  
        
          if (jComboBoxCar.getSelectedItem().equals("BMW_X6") && jComboBoxTradeIn.getSelectedItem().equals("TRADE IN CAR"))
        {
           String iSubtotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(BMW_X6 + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount()+cFindTax(BMW_X6 + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }
          
            if (jComboBoxCar.getSelectedItem().equals("BenzCLK") && jComboBoxTradeIn.getSelectedItem().equals("TRADE IN CAR"))
        {
            String Car = String.format("$%.2f", BenzCLK + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }
          
             if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro") && jComboBoxTradeIn.getSelectedItem().equals("TRADE IN CAR"))
        {
            String Car = String.format("$%.2f", Chevolet_Camaro + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
             
              if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler") && jComboBoxTradeIn.getSelectedItem().equals("TRADE IN CAR"))
        {
            String Car = String.format("$%.2f", Jeep_Wrangler + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
              
               if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom") && jComboBoxTradeIn.getSelectedItem().equals("TRADE IN CAR"))
        {
            String Car = String.format("$%.2f", RollsRoyce_Phantom + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
               
       //================================1 - 5000===============================================================================================================================
       
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT") && jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {   FordMustangGT = FordMustangGT - 10000;
            String iSubtotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(FordMustangGT + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount()+cFindTax(FordMustangGT + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }  
        
          if (jComboBoxCar.getSelectedItem().equals("BMW_X6") && jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {  BMW_X6 = BMW_X6 - 10000;
           String iSubtotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(BMW_X6 + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount()+cFindTax(BMW_X6 + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }
          
            if (jComboBoxCar.getSelectedItem().equals("BenzCLK") && jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {   BenzCLK = BenzCLK - 10000;
            String Car = String.format("$%.2f", BenzCLK + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }
          
             if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro") && jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {   Chevolet_Camaro = Chevolet_Camaro - 10000;
            String Car = String.format("$%.2f", Chevolet_Camaro + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
             
              if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler") && jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {   Jeep_Wrangler = Jeep_Wrangler - 10000;
            String Car = String.format("$%.2f", Jeep_Wrangler + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
              
               if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom") && jComboBoxTradeIn.getSelectedItem().equals("1 - 5000"))
        {   RollsRoyce_Phantom = RollsRoyce_Phantom - 10000;
            String Car = String.format("$%.2f", RollsRoyce_Phantom + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
               
     //================================5001 - 20000===============================================================================================================================
        
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT") && jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {   FordMustangGT = FordMustangGT - 8000;
            String iSubtotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(FordMustangGT + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount()+cFindTax(FordMustangGT + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }  
        
          if (jComboBoxCar.getSelectedItem().equals("BMW_X6") && jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {  BMW_X6 = BMW_X6 - 8000;
           String iSubtotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(BMW_X6 + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount()+cFindTax(BMW_X6 + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }
          
            if (jComboBoxCar.getSelectedItem().equals("BenzCLK") && jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {   BenzCLK = BenzCLK - 8000;
            String Car = String.format("$%.2f", BenzCLK + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }
          
             if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro") && jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {   Chevolet_Camaro = Chevolet_Camaro - 8000;
            String Car = String.format("$%.2f", Chevolet_Camaro + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
             
              if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler") && jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {   Jeep_Wrangler = Jeep_Wrangler - 8000;
            String Car = String.format("$%.2f", Jeep_Wrangler + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
              
               if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom") && jComboBoxTradeIn.getSelectedItem().equals("5001 - 20000"))
        {   RollsRoyce_Phantom = RollsRoyce_Phantom - 8000;
            String Car = String.format("$%.2f", RollsRoyce_Phantom + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
               
     //================================20001 - 50000===============================================================================================================================
       
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT") && jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        { FordMustangGT = FordMustangGT - 6000;
            String iSubtotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(FordMustangGT + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount()+cFindTax(FordMustangGT + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }  
        
          if (jComboBoxCar.getSelectedItem().equals("BMW_X6") && jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        {  BMW_X6 = BMW_X6 - 6000;
           String iSubtotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(BMW_X6 + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount()+cFindTax(BMW_X6 + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }
          
            if (jComboBoxCar.getSelectedItem().equals("BenzCLK") && jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        {   BenzCLK = BenzCLK - 6000;
            String Car = String.format("$%.2f", BenzCLK + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }
          
             if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro") && jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        {   Chevolet_Camaro = Chevolet_Camaro - 6000;
            String Car = String.format("$%.2f", Chevolet_Camaro + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
             
              if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler") && jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        {   Jeep_Wrangler = Jeep_Wrangler - 6000;
            String Car = String.format("$%.2f", Jeep_Wrangler + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
              
               if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom") && jComboBoxTradeIn.getSelectedItem().equals("20001 - 50000"))
        {   RollsRoyce_Phantom = RollsRoyce_Phantom - 6000;
            String Car = String.format("$%.2f", RollsRoyce_Phantom + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
               
     //================================50001 - 100000===============================================================================================================================
        
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT") && jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {   FordMustangGT = FordMustangGT - 4000;
            String iSubtotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(FordMustangGT + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount()+cFindTax(FordMustangGT + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }  
        
          if (jComboBoxCar.getSelectedItem().equals("BMW_X6") && jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {  BMW_X6 = BMW_X6 - 4000;
           String iSubtotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(BMW_X6 + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount()+cFindTax(BMW_X6 + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }
          
            if (jComboBoxCar.getSelectedItem().equals("BenzCLK") && jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {   BenzCLK = BenzCLK - 4000;
            String Car = String.format("$%.2f", BenzCLK + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }
          
             if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro") && jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {   Chevolet_Camaro = Chevolet_Camaro - 4000;
            String Car = String.format("$%.2f", Chevolet_Camaro + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
             
              if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler") && jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {   Jeep_Wrangler = Jeep_Wrangler - 4000;
            String Car = String.format("$%.2f", Jeep_Wrangler + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
              
               if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom") && jComboBoxTradeIn.getSelectedItem().equals("50001 - 100000"))
        {   RollsRoyce_Phantom = RollsRoyce_Phantom - 4000;
            String Car = String.format("$%.2f", RollsRoyce_Phantom + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
               
     //================================100001 - 500000===============================================================================================================================
       
        if (jComboBoxCar.getSelectedItem().equals("FordMustangGT") && jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {  FordMustangGT = FordMustangGT - 2000;
            String iSubtotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(FordMustangGT + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", FordMustangGT + Accessory.GetAmount()+cFindTax(FordMustangGT + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }  
        
          if (jComboBoxCar.getSelectedItem().equals("BMW_X6") && jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {  BMW_X6 = BMW_X6 - 2000;
           String iSubtotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount());
            String iTax = String.format("$%.2f", cFindTax(BMW_X6 + Accessory.GetAmount()));
            String iTotal = String.format("$%.2f", BMW_X6 + Accessory.GetAmount()+cFindTax(BMW_X6 + Accessory.GetAmount()));           
            jTextFieldTax.setText(iTax);
            jTextFieldSubtotal.setText(iSubtotal);
            jTextFieldTotal.setText(iTotal);
        }
          
            if (jComboBoxCar.getSelectedItem().equals("BenzCLK") && jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {   BenzCLK = BenzCLK - 2000;
            String Car = String.format("$%.2f", BenzCLK + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }
          
             if (jComboBoxCar.getSelectedItem().equals("Chevolet_Camaro") && jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {   Chevolet_Camaro = Chevolet_Camaro - 2000;
            String Car = String.format("$%.2f", Chevolet_Camaro + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
             
              if (jComboBoxCar.getSelectedItem().equals("Jeep_Wrangler") && jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {   Jeep_Wrangler = Jeep_Wrangler - 2000;
            String Car = String.format("$%.2f", Jeep_Wrangler + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
              
               if (jComboBoxCar.getSelectedItem().equals("RollsRoyce_Phantom") && jComboBoxTradeIn.getSelectedItem().equals("100001 - 500000"))
        {   RollsRoyce_Phantom = RollsRoyce_Phantom - 2000;
            String Car = String.format("$%.2f", RollsRoyce_Phantom + Accessory.GetAmount());
            jTextFieldTax.setText(Car);
            jTextFieldSubtotal.setText(Car);
            jTextFieldTotal.setText(Car);
        }  
               
       //============================RECEIPT=================================== 
       
       jTextAreaReceipt.append("\tDON ROSS AUTOHEAD" + "\n" +
       "*******************************************************************************************" + "\n");
       jTextAreaReceipt.append("CUSTOMER ID" + "\t\t\t" + jTextFieldCustomer.getText() + "\n");
       jTextAreaReceipt.append("FIRSTNAME" + "\t\t\t" + jTextFieldFirstname.getText() + "\n");
       jTextAreaReceipt.append("SURNAME" + "\t\t\t" + jTextFieldSurname.getText() + "\n");
       jTextAreaReceipt.append("ADDRESS" + "\t\t\t" + jTextFieldAddress.getText() + "\n");
       jTextAreaReceipt.append("PHONE NO" + "\t\t\t" + jTextFieldPhone.getText() + "\n");
       jTextAreaReceipt.append("STATE OF RESIDENCE" + "\t\t\t" + jTextFieldSOR.getText() + "\n");
       jTextAreaReceipt.append("PROVE OF ID" + "\t\t\t" + jComboBoxPOID.getSelectedItem() + "\n");
       jTextAreaReceipt.append("***************************************************" + "\n");
       jTextAreaReceipt.append("DOWN PAYMENT" + "\t\t\t" + jTextFieldDownP.getText() + "\n");
       jTextAreaReceipt.append("TYPE OF CAR" + "\t\t\t" + jComboBoxCar.getSelectedItem() + "\n");
       jTextAreaReceipt.append("CAR COST" + "\t\t\t" + jTextFieldCost.getText() + "\n");
       jTextAreaReceipt.append("VALUE OF TRADE" + "\t\t\t" + jTextFieldValue.getText() + "\n");
       jTextAreaReceipt.append("------------------------------------------------------------------------" + "\n");
       jTextAreaReceipt.append("TAX" + "\t\t\t" + jTextFieldTax.getText() + "\n");
       jTextAreaReceipt.append("SUBTOTAL" + "\t\t\t" + jTextFieldSubtotal.getText() + "\n");
       jTextAreaReceipt.append("TOTAL" + "\t\t\t" + jTextFieldTotal.getText() + "\n");
       jTextAreaReceipt.append("------------------------------------------------------------------------" + "\n");
      
    
    
    }//GEN-LAST:event_jButtonTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoHead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckBoxGPS;
    private javax.swing.JCheckBox jCheckBoxLeather;
    private javax.swing.JCheckBox jCheckBoxMPB;
    private javax.swing.JCheckBox jCheckBoxStereo;
    private javax.swing.JCheckBox jCheckBoxTint;
    private javax.swing.JComboBox<String> jComboBoxCar;
    private javax.swing.JComboBox<String> jComboBoxPOID;
    private javax.swing.JComboBox<String> jComboBoxTradeIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextAreaReceipt;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldCustomer;
    private javax.swing.JTextField jTextFieldDownP;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSOR;
    private javax.swing.JTextField jTextFieldSubtotal;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldTax;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldValue;
    // End of variables declaration//GEN-END:variables
}
